############################################
####### ChestHarvester Configuration #######
############################################

# if true, chests will pickup drops
AutoCollect: true

# default is 5 seconds
AutoCollectScanInterval: 5

# if true, scans in a full box area for chests
# false scans sides & top
scanFull: false 

# range from 1 - 3
# (1 is fastest, 3 takes more load to process)
scanDistance: 1

# if storage minecarts should colleact, too
storageCartsCollect: false
# if chests should empty storage minecarts traveling by
storageCartsEmpty: false


# if normally unstackables should stack
#   stacks: apples, bows, bread, pork, cookedpork, fish, cookedfish, signs, 
#       doors, carts, saddles, snowballs, boats, eggs, cake, beds, records
AutoStack: true

# for collecting or harvesting, what worlds (if any) will not be scanned
#			(comma-delimited, case insensitive)
disabledWorlds: 

# when a chest is clicked, should it harvest the nearby area?
ManualHarvest: true
# if chests should harvest when activated by redstone
RedstoneHarvest: false
# min. wait before can farm again for a given chest (seconds)
ManualHarvestWaitInterval: 2
# if permissions are use for harvesting (ChestHarvester.harvest)
ManualHarvestPermissions: false
harvesting:
    # max. distance from the chest will harvest
    range: 5
    # height is the max difference up/down from the height where the chest is
    height: 1
    # if harvest in the direction the player is looking
    #   (if false, will harvest in a box around the chest)
    directional: true
    # if directional, should corners also be a direction? (eg. north-east)
    # (if false, will only harvest in linear direction - N/E/S/W)
    harvestCorners: true
    # if useBonemeal, will use any bonemeal in the chest to unfinished crops before harvesting
    useBonemeal: true
    # when clicked (if seeds are availiable), should the harvester till new land to plant on?
    autotill: true
    # if new land requires a hoe to till with
    useHoe: true
    # if seeds are replanted after harvesting
    # (if false, also disables tilling)
    replant: true
    # if should be able to harvest wheat
    # (if false, also disables tilling)
    harvestWheat: true
    # if should be able to harvest sugarcane
    harvestReeds: true
    # if should be able to harvest cactus
    harvestCactus: true
    # if should be able to harvest pumpkins
    harvestPumpkins: true
    # if should be able to harvest melons
    harvestMelons: true
