name: ChestHarvester
main: me.jascotty2.chestharvester.ChestHarvester
version: 1.3.5
website: https://github.com/jascotty2/ChestHarvester/
author: jascotty2
description: >
             Turns chests into stationary farming equipment
commands:
  chestharvester:
    description: Admin Commands
    usage: /<command> [reload]
    aliases: [chh]